inform_get/apps/accounts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views.static import serve

urlpatterns = [
    url(r'^reset_passwd/$', views.reset_passwd, name='reset_passwd'),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$',views.logout, name='logout'),
    url(r'^$', views.change_passwd, name='change_passwd'),
    url(r'^reset_passwd/$', views.reset_passwd, name='reset_passwd'),
    url(r'^ldap_set/$', views.ldap_set, name="ldap_set"),
    url(r'^pause/$', views.pause, name="pause"),
    url(r'^option_rec/$', views.option_rec, name="option_rec")
]

inform_get/apps/apis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views.static import serve

urlpatterns = [
    url(r'^user_info/', views.users_ad_info, name='user_info'),
]

inform_get/apps/cicd/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views.static import serve

urlpatterns = [
    url(r'^$', views.get_ou, name='get_ou'),
    url(r'^users', views.users, name='users')

]

inform_get/inform_get/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('apps.accounts.urls','accounts'), namespace="accounts")),
    url(r'^api/', include(('apps.apis.urls','apis'), namespace="apis")),
    url(r'^cicd/', include(('apps.cicd.urls', 'cicd'), namespace='cicd'))

]

inform_get/apps/accounts/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    uid = models.AutoField(primary_key=True)
    userid = models.CharField(max_length=30)
    name = models.CharField(max_length=40)
    position = models.CharField(max_length=60)
    mobile = models.CharField(max_length=20)
    email = models.CharField(max_length=40)
    deployment = models.ForeignKey('Deployment', on_delete=models.DO_NOTHING)
    isLeader = models.BooleanField()
    isActive = models.BooleanField()
    syncmask = models.SmallIntegerField(default=0)
    utime = models.DateTimeField('更新时间')
    ctime = models.DateTimeField(auto_now=True)


class Deployment(models.Model):
    uid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    path = models.CharField(max_length=200)
    level = models.IntegerField('层级')
    present = models.BooleanField()
    utime = models.DateTimeField('更新时间')
    ctime = models.DateTimeField(auto_now=True)

inform_get/apps/apis/models.py
from django.db import models

# Create your models here.

inform_get/apps/cicd/models.py
from django.db import models

# Create your models here.

inform_get/apps/accounts/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import check_password as auth_check_password

inform_get/apps/accounts/views.py
from django.shortcuts import render, reverse, redirect,HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# auth主认证模块
from django.contrib import auth
# 对应数据库，可以创建添加记录
from django.contrib.auth.models import User


def login(request):
    next = request.GET.get('next', '')
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("pass")
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            if next == "":
                return HttpResponseRedirect(reverse('accounts:change_passwd'))
            else:
                return HttpResponseRedirect(next)
        else:
            # 登陆失败
            return render(request, 'login.html')
    return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect(reverse("accounts:login"))



def reset_passwd(request):
    return render(request, "reset_passwd.html")

@login_required
def change_passwd(request):
    return render(request, "change_passwd.html")


def ldap_set(request):
    return render(request, "ldap_set.html")

# @login_required()
def pause(request):
    return render(request, "pause.html")
# def base(request):
#     return render(request, "base.html")

# @login_required()
def option_rec(request):
    return render(request, "option_rec.html")

# # Create your views here.
# def login(request):
#     if request.method == 'POST':
#         login_form = forms.UserForm(request.POST)
#         message = '请检查填写的内容！'
#         if login_form.is_valid():
#             username = login_form.cleaned_data.get('username')
#             password = login_form.cleaned_data.get('password')
#
#             try:
#                 user = models.User.objects.get(name=username)
#             except :
#                 message = '用户不存在！'
#                 return render(request, 'login/login.html', locals())
#
#             if user.password == password:
#                 return redirect('/index/')
#             else:
#                 message = '密码不正确！'
#                 return render(request, 'login/login.html', locals())
#         else:
#             return render(request, 'login/login.html', locals())
#
#     login_form = forms.UserForm()
#     return render(request, 'login/login.html', locals())

inform_get/apps/apis/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http import JsonResponse
from django.views.generic import View
# Create your views here.
from libs.ldap_users import UserLdap




def users_ad_info(request):
    g = UserLdap()
    ret_info = g.get_userinfo()
    return JsonResponse(ret_info, safe=False)

inform_get/apps/cicd/views.py
from django.shortcuts import render
from libs.ldap_users import UserLdap
import json
# Create your views here.
def get_ou(request):
    pass

def users(request):
    g = UserLdap()
    ret_info = g.get_userinfo()
    return render(request, 'user_info.html' ,{"ret_info": ret_info})

inform_get/inform_get/views.py
from django.shortcuts import HttpResponse,render

from django.shortcuts import render

# Create your views here.

inform_get/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=100">
  <title>WinodwAD</title>

  <!-- Tell the browser to be responsive to screen width -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'assets/adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
{#  <link rel="stylesheet" href="{% static 'assets/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">#}
  <!-- iCheck -->

  <link rel="stylesheet" href="{% static 'assets/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
{#  <link rel="stylesheet" href="{% static 'assets/adminlte/plugins/jqvmap/jqvmap.min.css' %}">#}
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'assets/adminlte/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'assets/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'assets/adminlte/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'assets/adminlte/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
{#  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">#}

    <link rel="stylesheet" href="{% static 'css/bash.css' %}">

</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>



    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
{#      {% if request.user.is_authenticated %}#}
    <ul class="navbar-nav ml-auto">
      <li class="dropdown" style="float: right;">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <img alt="" src="#" height="30px">
            <span class="username">
                {% if request.user.is_authenticated %}
                    {{ user.username }}
                {% endif %}
            </span>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" style="rgba(0,0,0,.5);">
            <div class="log-arrow-up"></div>
            <li><a class="" href="#" > 个人资料 </a></li>
            <li><a class="" href="#"> 修改密码 </a></li>
            <li><a class="" href="#"> 我的回答 </a></li>
            <li><a class="" href="#"> 我的收藏 </a></li>
            <li><a class="" href="#"> 我的贡献 </a></li>
            <li><a class="" href="{% url 'accounts:logout' %}"> 退出 </a></li>
        </ul>
    </li>

    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4" style="font-size: 13px; ">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static '/assets/adminlte/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">WindowAD</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'assets/adminlte/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block" style="font-size: 16px;">{{ user.last_name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active trees">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                ADmon
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'accounts:change_passwd' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>修改密码</p>
                </a>
              </li>
              <li class="nav-item">
                {% if user.is_authenticated and user.is_superuser %}
                <a href="{% url 'accounts:ldap_set' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>同步设置(管理员)</p>
                </a>
              </li>
            {% endif %}
              <li class="nav-item">
                {% if user.is_authenticated and user.is_superuser %}
                <a href="{% url 'accounts:pause' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>暂停/删除用户(管理员)</p>
                </a>
              </li>
            {% endif %}
              <li class="nav-item">
                  {% if user.is_authenticated and user.is_superuser %}
                      <a href="{% url 'accounts:option_rec' %}" class="nav-link">

                  <i class="far fa-circle nav-icon"></i>
                  <p>操作记录(管理员)</p>
                </a>
              </li>
            {% endif %}
            </ul>
          </li>

          <li class="nav-item has-treeview">
            <a href="#" class="nav-link trees">
              <i class="nav-icon fas fa-tree"></i>
              <p>
                CICD
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
{#                <a href="{% url 'cicd:user_info' %}" class="nav-link {% block active_usr_extends %}{% endblock %}">#}
                  <a href="{% url 'cicd:user' %}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                  <p>用户信息</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="font-size: 12.5px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">ADmon</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
            {% block content %}{% endblock %}
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    <footer class="main-footer" style="padding: 0.5rem; font-size: 13px">
        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
          <b>Version</b> 3.0.5
        </div>
    </footer>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'assets/adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'assets/adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'assets/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'assets/adminlte/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'assets/adminlte/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
{#<script src="{% static 'assets/adminlte/plugins/jqvmap/jquery.vmap.min.js' %}"></script>#}
{#<script src="{% static 'assets/adminlte/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>#}
<!-- jQuery Knob Chart -->
<script src="{% static 'assets/adminlte/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'assets/adminlte/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'assets/adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
{#<script src="{% static 'assets/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>#}
<!-- Summernote -->
<script src="{% static 'assets/adminlte/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'assets/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'assets/adminlte/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{#<script src="{% static 'assets/adminlte/dist/js/pages/dashboard.js' %}"></script>#}
<!-- AdminLTE for demo purposes -->
<script src="{% static 'assets/adminlte/dist/js/demo.js' %}"></script>

<script>
    $(function () {
        $('.nav-sidebar').find("li").removeClass('menu-open');
        $('.nav-sidebar').find("a").removeClass('active');
        $('.nav-sidebar').find("a").each(function () {
            if(this.href === window.location.href) {
                $(this).addClass('active');
                $(this).closest('.has-treeview').addClass('menu-open');
                $('.nav-sidebar').find('.menu-open').children('.trees').addClass('active');
            }
        });
    });
</script>

</body>
</html>

inform_get/templates/change_passwd.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


        <!-- Small boxes (Stat box) -->
        <div  class="row">
            <form method="POST" style="width:300px; margin:100px auto">
            {% csrf_token %}
                <div class="form-group">
                    <input type="password" class="form-control" name="oldpassword" id="psw" placeholder="旧密码">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="newpassword1" id="npsw" placeholder="新密码">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="newpassword2" id="cpsw" placeholder="确认新密码">
                </div>
                <button type="button" class="btn btn-default" id="btn1" style="float: right">提交</button></br>
                <span id="ret_info"></span>
            </form>
        </div>

{% endblock %}

inform_get/templates/ldap_set.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div style="width: 100%; height:100%;text-align: center">
<form style="display: inline-block">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">账号同步检测周期</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="scan" placeholder="默认1分钟">
        </div>
    </div>

  <div class="form-group row">
      <label  class="col-sm-2 col-form-label">是否开启确认模式</label>
       <div class="col-sm-10">
          <div class="col-sm-10">
        <button type="button" class="btn btn-primary btn-sm" style="margin-top: 10px; " id="btn_true">是</button>
        <button type="button" class="btn btn-secondary btn-sm" style="margin-top: 10px;" id="btn_false">否</button>
    </div>
    </div>
  </div>
 <div class="form-group row">
     <label  class="col-sm-2 col-form-label">同步组件</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" placeholder="邮箱|钉钉|redmine">
    </div>
  </div>

<div class="line">ldap设置</div>


    <div class="form-group row">
        <label for="ldap_url" class="col-sm-2 col-form-label">ldap地址</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="ldap_url">
    </div>
  </div>

  <div class="form-group row">
    <label for="bind_dn" class="col-sm-2 col-form-label">绑定DN</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="bind_dn">
    </div>
  </div>
 <div class="form-group row">
        <label for="inputPassword" class="col-sm-2 col-form-label">密码</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword">
    </div>
  </div>
 <div class="form-group row">
        <label for="url_ou" class="col-sm-2 col-form-label">用户OU</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="url_ou">
    </div>
  </div>
 <div class="form-group row">
        <label for="url_filter" class="col-sm-2 col-form-label">用户过滤器</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="url_filter">
    </div>
  </div>
    <button type="submit" class="btn btn-default" style="float: right">测试连接</button>

</form>
</div>
{% endblock %}

inform_get/templates/ldap_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

inform_get/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>扁平而简洁的登录页面模板-bootschool.net</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/log_in/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/log_in/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/log_in/css/main.css' %}">
</head>
<body>
<div class="container">
    <div class="wrap-login">
        <div class="wrap-form-title" style="background-image: url(/static/assets/log_in/images/banner.jpg);">
            <span class="form-title">登 录</span>
        </div>

        <form class="login-form validate-form" method="POST">
            {% csrf_token %}
            <div class="wrap-input validate-input m-b-26" data-validate="用户名不能为空">
                <label class="label-input">用户名:</label>
                <input class="input" type="text" id="username" name="username" autocomplete="off" placeholder="请输入用户名">
                <span class="focus-input"></span>
            </div>

            <div class="wrap-input validate-input m-b-18" data-validate="密码不能为空">
                <label class="label-input">密&nbsp;&nbsp;&nbsp;&nbsp;码:</label>
                <input class="input" type="password" id="pass" name="pass" placeholder="请输入密码">
                <span class="focus-input"></span>
            </div>

            <div class="flex-sb-m w-full p-b-30">
                <div class="contact-form-checkbox">
                    <input class="input-checkbox" id="ckb1" type="checkbox" name="remember-me">
                    <label class="label-checkbox" for="ckb1">记住我</label>
                </div>
                <div>
                    <a href="{% url 'accounts:reset_passwd' %}" class="txt1">忘记密码？</a>
                </div>
            </div>

            <div class="wrapper-form-btn">
                <button class="login-form-btn">登 录</button>
            </div>
        </form>
    </div>
</div>
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
{#<script src="{% static 'assets/log_in/js/main.js' %}"></script>#}
<script>

</script>

</body>
</html>

inform_get/templates/option_rec.html
{% extends 'base.html' %}
{% load static %}

{%block active_opt_extends%}active{%endblock%}"

{% block content %}



<table class="table table-bordered">
  <thead>
    <tr>
      <th>日志ID</th>
      <th>索引目录</th>
      <th>操作者</th>
      <th>操作信息</th>
      <th>操作时间</th>
    </tr>
  </thead>
</table>
{% endblock %}

inform_get/templates/pause.html
{% extends 'base.html' %}
{% load static %}


"nav-link {%block active_pau_extends%}active{%endblock%}"

{% block content %}


<form class="form-inline">
  <div class="form-group mb-2">
    <label for="op_username" class="sr-only">用户名</label>
    <input type="text" readonly class="form-control-plaintext" id="op_username" value="用户名">
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <label for="inputPassword2" class="sr-only">Password</label>
    <input type="text" class="form-control" id="inputPassword2" placeholder="Password">
  </div>
    <button type="submit" class="btn btn-default" style="margin-bottom: 7px; ">暂停</button>

    <button type="submit" class="btn btn-default" style="margin-bottom: 7px; ">删除</button>
</form>
{% endblock %}

inform_get/templates/reset.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


    <div  class="row">
        <form method="POST" style="width:300px; margin:100px auto">
        {% csrf_token %}
            <div class="form-group">
                <input type="password" class="form-control" name="newpassword3" id="npsw1" placeholder="新密码">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="newpassword4" id="cpsw1" placeholder="新密码">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="mobile_captcha" id="mobile_captcha" placeholder="短信验证码" style="width: 60%; display:inline;">
                <input type="button" class="btn btn-default" id="btn3" value="获取手机验证码">
            </div>
            <button type="button" class="btn btn-default" id="btn4" style="float: right">提交</button></br>
            <span id="ret_info"></span>
        </form>
    </div>

    
    
    
    
    
{% endblock %}

inform_get/templates/reset_passwd.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>bootschool.net</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/log_in/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/log_in/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/log_in/css/main.css' %}">
</head>
<body>
<div class="container">
    <div class="wrap-login">
        <div class="wrap-form-title" style="background-image: url(/static/assets/log_in/images/banner.jpg);">
            <span class="form-title">重 置</span>
        </div>

        <form class="login-form validate-form" method="POST">
            {% csrf_token %}
            <div class="wrap-input validate-input m-b-26" data-validate="用户名不能为空">
                <label class="label-input">新密码:</label>
                <input class="input" type="text" id="username" name="username" autocomplete="off" placeholder="请输入用户名">
                <span class="focus-input"></span>
            </div>

            <div class="wrap-input validate-input m-b-18" data-validate="密码不能为空">
                <label class="label-input">新密码:</label>
                <input class="input" type="password" id="npass" name="npass" placeholder="请输入密码">
                <span class="focus-input"></span>
            </div>

            <div class="wrap-input validate-input m-b-18" data-validate="密码不能为空">
                <label class="label-input">短信验证码:</label>
                <input class="input" type="text" id="mobile_captcha" name="mobile_captcha" placeholder="短信验证码">
                <span class="focus-input" ></span>
            </div>

            <div style="display: inline-block; margin-bottom: 20px;" >
{#                <input  id="mobile_captcha" type="button" name="mobile_captcha" value="获取短信验证码" >#}
                <input onclick="sendmessage(this,60);" type="button" value="发送短信"  class="btn btn-info" style="height:38px;width: 125px;"/>
                <a href="{% url 'accounts:login' %}" class="txt1" style="margin-left: 160px">登录</a>
            </div>

            <div class="wrapper-form-btn">
                <button class="login-form-btn">提交</button>
            </div>
        </form>
    </div>
</div>
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

<script>

</script>

</body>
</html>